model_list:
  - model_name: *
    litellm_params:
      model: *
      aws_region_name: os.environ/AWS_REGION
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
